export const items = [
  {
    id: Math.random(),
    title: "breakfast 1",
    description: "This is a breakfast",
    category: "breakfast",
    price: "50$",
    img: `img${((Math.random() * 10 + 0.5) / 2).toFixed()}.jpg`,
  },
  {
    id: Math.random(),
    title: "breakfast 2",
    description: "This is a breakfast",
    category: "breakfast",
    price: "50$",
    img: `img${((Math.random() * 10 + 0.5) / 2).toFixed()}.jpg`,
  },
  {
    id: Math.random(),
    title: "Lunch 1",
    description: "This is a Lunch",
    category: "lunch",
    price: "50$",
    img: `img${((Math.random() * 10 + 0.5) / 2).toFixed()}.jpg`,
  },
  {
    id: Math.random(),
    title: "Lunch 2",
    description: "This is a Lunch",
    category: "lunch",
    price: "50$",
    img: `img${((Math.random() * 10 + 0.5) / 2).toFixed()}.jpg`,
  },
  {
    id: Math.random(),
    title: "Dinner 1",
    description: "This is a Dinner",
    category: "dinner",
    price: "50$",
    img: `img${((Math.random() * 10 + 0.5) / 2).toFixed()}.jpg`,
  },
  {
    id: Math.random(),
    title: "Dinner 2",
    description: "This is a Dinner",
    category: "dinner",
    price: "50$",
    img: `img${((Math.random() * 10 + 0.5) / 2).toFixed()}.jpg`,
  },
];
